In [3]:
import pandas as pd
import datetime

data = {
    "ProductID": [101, 102, 103, 104, 105],                     # numeric (int)
    "Price": [249.99, 199.50, 349.00, 129.99, 499.99],          # numeric (float)
    "ProductName": [
        "Wireless Headphones",
        "Bluetooth Speaker",
        "Smartwatch",
        "Gaming Mouse",
        "Laptop Stand"
    ],                                                          # text (string)
    "Category": [
        "Electronics",
        "Audio",
        "Wearables",
        "Accessories",
        "Office"
    ],                                                          # text (string)
    "LaunchDate": [
        datetime.date(2023, 5, 15),
        datetime.date(2023, 6, 1),
        datetime.date(2023, 7, 20),
        datetime.date(2023, 8, 10),
        datetime.date(2023, 9, 5)
    ],                                                          # date type
    "LastUpdated": [
        datetime.datetime(2024, 1, 10, 14, 30),
        datetime.datetime(2024, 2, 5, 9, 15),
        datetime.datetime(2024, 3, 12, 18, 45),
        datetime.datetime(2024, 4, 8, 11, 0),
        datetime.datetime(2024, 5, 2, 16, 20)
    ]                                                           # datetime type
}

# print(data)

df = pd.DataFrame(data)
print(df.head())

# Filtering
# sprint(df[(df['ProductID']==101) & (df['Price'] < 400)])

# print("Lambda", df[['Category','Price']].apply(lambda x : 1 if x[0] == 'Audio' and x[1] < 200 else 0,axis=1))

# Group By
# print(df.groupby('ProductID',as_index=False).agg({'Price':sum}))

# Sorting
# print(df.sort_values(by=['Price','LastUpdated'],ascending=[False,True]))

# DateTime
# print(pd.to_datetime(df['LastUpdated'],format='%Y-%m').dt.month)

# Null Values
# print(df[df.isnull()].count())
# /len(df)*100)

   ProductID   Price          ProductName     Category  LaunchDate  \
0        101  249.99  Wireless Headphones  Electronics  2023-05-15
1        102  199.50    Bluetooth Speaker        Audio  2023-06-01
2        103  349.00           Smartwatch    Wearables  2023-07-20
3        104  129.99         Gaming Mouse  Accessories  2023-08-10
4        105  499.99         Laptop Stand       Office  2023-09-05

          LastUpdated
0 2024-01-10 14:30:00
1 2024-02-05 09:15:00
2 2024-03-12 18:45:00
3 2024-04-08 11:00:00
4 2024-05-02 16:20:00

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    5 non-null      int64
 1   Price        5 non-null      float64
 2   ProductName  5 non-null      object
 3   Category     5 non-null      object
 4   LaunchDate   5 non-null      object
 5   LastUpdated  5 non-null      datetime64[ns]
 6   Test_Col     5 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 412.0+ bytes

In [14]:
df.head()

,ProductID,Price,ProductName,Category,LaunchDate,LastUpdated,Test_Col
0,101,249.99,Wireless Headphones,Electronics,2023-05-15,2024-01-10 14:30:00,High
1,102,199.50,Bluetooth Speaker,Audio,2023-06-01,2024-02-05 09:15:00,0
2,103,349.00,Smartwatch,Wearables,2023-07-20,2024-03-12 18:45:00,High
3,104,129.99,Gaming Mouse,Accessories,2023-08-10,2024-04-08 11:00:00,0
4,105,499.99,Laptop Stand,Office,2023-09-05,2024-05-02 16:20:00,High

In [5]:
df.loc[:,'Test_Col'] = 0

In [13]:
df.loc[df['Price']> 200,'Test_Col'] = 'High'

C:\Users\Admin\AppData\Local\Temp\ipykernel_20008\2709825779.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'High' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Price']> 200,'Test_Col'] = 'High'

In [8]:
df[(df['Price'] > 200) & (df['ProductID']> 102)]

,ProductID,Price,ProductName,Category,LaunchDate,LastUpdated,Test_Col
2,103,349.00,Smartwatch,Wearables,2023-07-20,2024-03-12 18:45:00,0
4,105,499.99,Laptop Stand,Office,2023-09-05,2024-05-02 16:20:00,0

In [10]:
df[['Price','ProductID']].apply(lambda x: 1 if x[0] > 200 and x[1] > 102 else 0,axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20008\3379584090.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df[['Price','ProductID']].apply(lambda x: 1 if x[0] > 200 and x[1] > 102 else 0,axis=1)

0    0
1    0
2    1
3    0
4    1
dtype: int64

In [12]:
pd.to_datetime(df['LastUpdated'],format = '%Y-%m').dt.month

0    1
1    2
2    3
3    4
4    5
Name: LastUpdated, dtype: int32